# Generated by Django 5.1.4 on 2025-03-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='nickname',
            field=models.CharField(default='OUCer_1743231787', max_length=50, unique=True, verbose_name='昵称'),
        ),
    ]
